### ISSUE TITLE
packwiz deleted all the jar files in mod directory and replaced with toml files?

### ISSUE THREAD

**Issue by IITFA** [comp500/packwiz#21]
So, after resolving my prior issue, decided to try it on an install. Well, it seemed to work and even seemed to update some mods, but when I launched the game, no mods loaded. So, looked in the mods folder only to find nothing but toml files and no jar files anymore. I presume this is not intended.

EDIT: On a whim I tried cf install Abnormals Core (one of the mods in the pack) to see if it changed anything, but no. Still no mod jars anywhere to be found.

**Comment by IITFA** [comment]
Alright, after some poking around, it seems that something didn't do right. Looking in the index.toml file, it indexed everything but the mods. Looking in the pack.toml it references the index.toml.

So, now I'm wondering how in the world did that happen.

**Comment by comp500** [comment]
This is intended. The packwiz CLI produces and manipulates .toml metadata files, not mods, so you'll want to use packwiz-installer to actually install the modpack, see [this section of the readme](https://github.com/comp500/packwiz#packwiz-installer-for-pack-installation).

Note that packwiz isn't really designed for local mod management, it's designed primarily for distributing mods for use with servers, but with `packwiz serve` it does work reasonably well. I should probably make the documentation a bit more clear!

**Comment by IITFA** [comment]
Alright, understood. One more thing, is the index.toml file supposed to have indexed all sorts of files outside of the mods folder?

**Comment by IITFA** [comment]
This is why I ask the above:

Current version is: null
New version is: v0.3.0
Attempting to update...
Update successful!
Loading manifest file...
Loading pack file...
Checking local files...
Modpack name: . Minecraft
[FATAL] Failed to process index file: 
com.google.gson.JsonParseException: Failed to parse URI
	at link.infra.packwiz.installer.metadata.SpaceSafeURIParser.deserialize(SpaceSafeURIParser.kt:20)
	at link.infra.packwiz.installer.metadata.SpaceSafeURIParser.deserialize(SpaceSafeURIParser.kt:14)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:952)
	at com.google.gson.Gson.fromJson(Gson.java:925)
	at com.moandjiezana.toml.Toml.to(Toml.java:323)
	at link.infra.packwiz.installer.UpdateManager.processIndex(UpdateManager.kt:255)
	at link.infra.packwiz.installer.UpdateManager.start(UpdateManager.kt:200)
	at link.infra.packwiz.installer.UpdateManager.<init>(UpdateManager.kt:45)
	at link.infra.packwiz.installer.Main.startup(Main.kt:81)
	at link.infra.packwiz.installer.Main.<init>(Main.kt:115)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at link.infra.packwiz.installer.bootstrap.LoadJAR.start(LoadJAR.java:51)
	at link.infra.packwiz.installer.bootstrap.Main.<init>(Main.java:91)
	at link.infra.packwiz.installer.bootstrap.Main.main(Main.java:46)
Caused by: java.net.URISyntaxException: Malformed escape pair at index 45: XaeroWaypoints/Multiplayer_192.168.12.184/dim%0/mw$-1349549096_2.txt
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.scanEscape(URI.java:3041)
	at java.base/java.net.URI$Parser.scan(URI.java:3064)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3082)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3166)
	at java.base/java.net.URI$Parser.parse(URI.java:3125)
	at java.base/java.net.URI.<init>(URI.java:600)
	at link.infra.packwiz.installer.metadata.SpaceSafeURI.<init>(SpaceSafeURI.kt:17)
	at link.infra.packwiz.installer.metadata.SpaceSafeURIParser.deserialize(SpaceSafeURIParser.kt:18)
	... 26 more

**Comment by IITFA** [comment]
Alright, after a lot of tinkering about, this is what I get when launching Minecraft (none of the mods from the pack actually load).

https://pastebin.com/raw/bK2WMVvw

**Comment by comp500** [comment]
> 
> 
> Alright, understood. One more thing, is the index.toml file supposed to have indexed all sorts of files outside of the mods folder?

It will index files outside the mods folder, yes, but you can exclude files you don't want with a `.packwizignore` file (the same format as `.gitignore`)

> 
> 
> Alright, after a lot of tinkering about, this is what I get when launching Minecraft (none of the mods from the pack actually load).
> 
> https://pastebin.com/raw/X4aSk9Uj

Not sure what the issue is there... if the JAR files are actually in the mods folder of your instance, and are valid, it should work.
